global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "node-exporter"
    static_configs:
      - targets: ["amber.cabronita.com:9100"]
        labels:
          host: "amber"
      - targets: ["capri.cabronita.com:9100"]
        labels:
          host: "capri"
      - targets: ["dia.cabronita.com:9100"]
        labels:
          host: "dia"
      - targets: ["acadia.cabronita.com:9182"]
        labels:
          host: "acadia"
      - targets: ["prometheus.cabronita.com:9115"]
        labels:
          host: "blackbox-exporter"

  - job_name: "temper"
    scrape_interval: 60s
    static_configs:
      - targets: ["amber.cabronita.com:8000"]
        labels:
          sensor: "office"

  - job_name: 'blackbox-exporter'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - idorota.cabronita.com
        labels:
          host: idorota
      - targets:
          - iremi.cabronita.com
        labels:
          host: iremi
      - targets:
          - router.cabronita.com
        labels:
          host: router
      - targets:
          - xg.cabronita.com
        labels:
          host: xg
      - targets:
          - xl.cabronita.com
        labels:
          host: xl
      - targets:
          - xo.cabronita.com
        labels:
          host: xo
      - targets:
          - zen.cabronita.com
        labels:
          host: zen
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus.cabronita.com:9115
