FROM python:3.12.13-slim-trixie
ENV TZ='Europe/London'

WORKDIR /app
COPY requirements.txt temper.py .

RUN apt-get update \
    && apt-get install -y --no-install-recommends libusb-1.0-0 usbutils \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "./temper.py"]
