---

- name: Check if docker-ce repo is enabled
  ansible.builtin.command:
    cmd: dnf repolist --enabled docker-ce-stable
  register: repolist_output
  changed_when:
    - repolist_output.stdout == ""

- name: Add docker-ce repo
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: repolist_output.stdout == ""

- name: Install docker-ce packages
  ansible.builtin.package:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: present

- name: Enable docker service
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started

