---

- name: Include repos.yml
  ansible.builtin.include_tasks:
    file: repos.yml

- name: Install packages
  ansible.builtin.package:
    name:
      - rsync
      - telegraf
      - vim-enhanced
    state: present

- name: Deploy telegraf config
  ansible.builtin.copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: 0644
  notify: restart telegraf
