---

- name: Include repos.yml
  ansible.builtin.include_tasks:
    file: repos.yml

- name: Install packages
  ansible.builtin.package:
    name:
      - rsync
      - vim-enhanced
    state: latest

