---

- name: Start r3 container
  community.docker.docker_container:
    command: 192.168.1.3 -vv
    image: cabronita/rsvp:1.0-ubi8
    name: r3
    network_mode: host
    restart_policy: "unless-stopped"
    state: started
    user: 1000:1000

- name: Start r4 container
  community.docker.docker_container:
    command: 192.168.1.4 -vv
    image: cabronita/rsvp:1.0-ubi8
    name: r4
    network_mode: host
    restart_policy: "unless-stopped"
    state: started
    user: 1000:1000

