---

- name: Install packages
  ansible.builtin.dnf:
    name:
      - '@Xfce'
      - xrdp
    state: present

- name: Enable xrdp service
  ansible.builtin.systemd_service:
    name: xrdp
    enabled: true
    state: started

